[project]
name = "quilean"
version = "1.0.0"
description = "A fast and smart Python CLI tool to organize, clean and manage files"
authors = [{ name = "Your Name", email = "your@email.com" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.0",
    "rich>=13.0.0",
    "questionary>=2.0.0",
    "colorama>=0.4.6"
]

[project.scripts]
quilean = "quilean.cli:main"
